[package]
name = "citro3d-macros"
version = "0.1.0"
edition = "2024"
authors = ["Rust3DS Org"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
litrs = { version = "0.5.1", default-features = false }
quote = "1.0.40"
